providers:
  acs:
    url: <API_URL>
    api_token: <API_TOKEN>
    sender: 
      id: <SENDER_ID>
    template:
      name: <TEMPLATE_NAME>
      lang: "en"
receivers:
  - name: "on-call"
    provider: "acs"
    to: 
      - <PHONE_NUMBER>
    text: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} @ {{ .Labels.instance }}'
    
